### ISSUE TITLE
picofly toolbox limited to 64Kb update.bin

### ISSUE THREAD

**Issue by floxcap** [rehius/usk#6]
Even small additions to the firmware cause it to be unable to be upgraded via the toolbox.

**Comment by rehius** [comment]
The firmware itself [supports](https://github.com/rehius/usk/blob/1a39e9b46dac3ab7ddddad647d03575e41655dbb/payload.c#L522C30-L522C33) firmware updates up to 224 KB. The toolbox is not a part of this repo.

**Comment by floxcap** [comment]
Thanks. Resolved with toolbox rebuild with updated code :)
