### ISSUE TITLE
Firmware check

### ISSUE THREAD

**Issue by T501501** [rehius/usk#9]
Just checking if this firmware will work on a switch with hos 17.0.0 as I have heard of some issues.
Many thanks

**Comment by Quas7** [comment]
I updated a V2 just yesterday to 17.0.0 with all-in-one updater and daybreak for the emunand followed by official update for sysnand.
No issues with all the latest tools installed beforehand.
I think, there might be some cases where a retraining of the picofly might be required - reflashing with 2.75 triggers this quick and easy.

**Comment by T501501** [comment]
Thanks a lot for you quick response it is most appreciated

**Comment by Quas7** [comment]
The OLED did update as well with no issues.

**Comment by T501501** [comment]
Thanks for all your work in checking this out.

**Comment by Ch3ck3rM0n** [comment]
Did you update the sysnand via standard updater from the Switch OFW?

**Comment by Quas7** [comment]
Yes, I used the normal update procedure as for a non-modded console. For that, I pressed vol+ & vol- after power-on to bypass the picofly.

I have a fresh V2 with 17.0.0 and will install a picofly this weekend - I can give feedback on this one as well.

**Comment by rehius** [comment]
It has no dependency on the HOS version. However the things like Hekate or Atmosphere must be compatible with your system version.
